name: Google Cloud App Engine deploy

on:
  push:
    branches: ["main"]

jobs:
  production-deploy:
    if: github.repository == 'PJECZ/pjecz-hercules-flask'
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: "Check out the repository"
        uses: "actions/checkout@v3"

      - name: "Authenticate"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_KEY }}

      - name: "Deploy"
        uses: "google-github-actions/deploy-appengine@v1"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: "app.yaml"
          working_directory: "."
          promote: true
